# Site settings
title: Dmitry Krasnoukhov
description: >
  I am a %age% years old passion-driven Ruby, Javascript, and iOS engineer from Kiev, Ukraine. I use cutting-edge tech to bring beautiful apps and websites to users.
email: dmitry@krasnoukhov.com
phone: +38 (091) 949-41-66
dob: 1992-03-12
baseurl: ""
url: "http://www.krasnoukhov.com"

# Build settings
timezone: EET
source: source
markdown: kramdown
exclude: [vendor]
assets:
  cache: ../.cache
